# Generated by Django 3.0.8 on 2020-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200804_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Brass Idols', 'Brass Idols'), ('Dhoop/camphor', 'Dhoop/Camphor'), ('Diya', 'Diya'), ('Gem Stone and Jewelry', 'Gem Stone and Jewelry'), ('Havan Items', 'Havan Items'), ('Puja Thali', 'Puja Thalis'), ('Rangoli', 'Rangoli'), ('Rudraksha and Yantra', 'Rudraksh and Yantra'), ('chunris', 'Chunris'), ('god cloths', 'God Cloths'), ('idols', 'Godd Idols'), ('puja essentials', 'Puja Essentials'), ('puja kits', 'Puja Kits')], max_length=50),
        ),
    ]
