# Generated by Django 3.0.8 on 2020-08-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orders_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Payment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
